PizzaPlace/PizzaPlace/ViewModels/OrdersListViewModel.cs
using PizzaPlace.Models;

namespace PizzaPlace.ViewModels
{
    public class OrdersListViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Message { get; set; }
        public OrderStatus Status { get; set; }
    }
}

PizzaPlace/PizzaPlace/Pages/Admin/OrdersList.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Mappings;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;

namespace PizzaPlace.Pages.Admin
{
    public class OrdersListModel : PageModel
    {
        private readonly IOrderService _orderService;

        public OrdersListModel(IOrderService orderService)
        {
            _orderService = orderService;
        }

        public List<OrdersListViewModel> OrdersList { get; set; }

        public void OnGet()
        {
            var orders = _orderService.GetAll();

            OrdersList = orders.Select(x => x.ToOrderListViewModel()).ToList();
        }

        public IActionResult OnGetSetProcessed(int id)
        {
            _orderService.SetProcessed(id);
            return RedirectToPage();
        }
    }
}

PizzaPlace/PizzaPlace/Pages/Admin/OrdersList.cshtml
@page
@model PizzaPlace.Pages.Admin.OrdersListModel
@{
    ViewData["Title"] = "Orders list";
}


<h1>Orders List:</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Surname
            </th>
            <th>
                Phone
            </th>
            <th>
                Address
            </th>
            <th>
                Message
            </th>
            <th>
                Status
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in Model.OrdersList)
        {
            <tr>
                <td>@order.Name</td>
                <td>@order.Surname</td>
                <td>@order.Phone</td>
                <td>@order.Address</td>
                <td>@order.Message</td>
                <td>@order.Status</td>

                @if (order.Status == Models.OrderStatus.Pending)
                {
                    <td>
                        <a class="btn btn-success" asp-page="/Admin/OrdersList" asp-page-handler="SetProcessed" asp-route-id="@order.Id">Set Processed</a>
                    </td>
                }
                else
                {
                    <td class="text-success">Processed</td>
                }
            </tr>
        }
    </tbody>
</table>