PizzaPlace/PizzaPlace/Models/Order.cs
using System.ComponentModel.DataAnnotations;

namespace PizzaPlace.Models
{
    public class Order
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Surname { get; set; }

        [Required]
        public string Phone { get; set; }

        [Required]
        public string Address { get; set; }

        [Required]
        public string Message { get; set; }
    }
}

PizzaPlace/PizzaPlace/ViewModels/OrderViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace PizzaPlace.ViewModels
{
    public class OrderViewModel
    {
        [Required]
        public string Name { get; set; }

        [Required]
        public string Surname { get; set; }

        [Required]
        public string Phone { get; set; }

        [Required]
        public string Address { get; set; }

        [Required]
        public string Message { get; set; }
    }
}

PizzaPlace/PizzaPlace/Pages/ConfirmationPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PizzaPlace.Pages
{
    public class ConfirmationPageModel : PageModel
    {
        public string Message { get; set; }

        public void OnGetOrderCompleted()
        {
            Message = "Thanks for ordering. Enjoy your meal.";
        }

        public void OnGetSubscriptionCompleted()
        {
            Message = "Thanks for your subscription. Stay tuned for more offers and products";
        }
    }
}

PizzaPlace/PizzaPlace/Pages/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Mappings;
using PizzaPlace.Models;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;

namespace PizzaPlace.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly IMenuItemService _menuItemService;

        public DetailsModel(IMenuItemService menuItemService)
        {
            _menuItemService = menuItemService;
        }

        public MenuItemViewModel MenuItem { get; set; }

        public string ErrorMessage { get; set; }

        public void OnGet(string slug)
        {
            MenuItem menuItem = _menuItemService.GetBySlug(slug);

            if (menuItem == null)
            {
                ErrorMessage = "The item could not be found.";
            }
            else
            {
                MenuItem = menuItem.ToViewModel();
            }

        }
    }
}

PizzaPlace/PizzaPlace/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PizzaPlace.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

PizzaPlace/PizzaPlace/Pages/Home.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Mappings;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;
using System.Collections.Generic;
using System.Linq;

namespace PizzaPlace.Pages
{
    public class HomeModel : PageModel
    {
        private readonly IOfferService _offerService;

        public HomeModel(IOfferService offerService)
        {
            _offerService = offerService;
        }

        public List<OfferViewModel> Offers { get; set; }

        public void OnGet()
        {
            var offers = _offerService.GetAllValid();

            Offers = offers.Select(x => x.ToViewModel()).ToList();
        }
    }
}

PizzaPlace/PizzaPlace/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Mappings;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;
using System.Collections.Generic;
using System.Linq;

namespace PizzaPlace.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IOfferService _offerService;

        public IndexModel(IOfferService offerService)
        {
            _offerService = offerService;
        }

        public List<OfferViewModel> Offers { get; set; }

        public void OnGet()
        {
            var offers = _offerService.GetAllValid();

            Offers = offers.Select(x => x.ToViewModel()).ToList();
        }
    }
}

PizzaPlace/PizzaPlace/Pages/Menu.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Mappings;
using PizzaPlace.Models;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;
using System.Collections.Generic;
using System.Linq;

namespace PizzaPlace.Pages
{
    public class MenuModel : PageModel
    {
        private readonly IMenuItemService _menuItemService;

        public MenuModel(IMenuItemService menuItemService)
        {
            _menuItemService = menuItemService;
        }

        public List<MenuItemViewModel> MenuItems { get; set; }

        public void OnGet()
        {
            List<MenuItem> menuItems = _menuItemService.GetAll();
            MenuItems = menuItems.Select(x => x.ToViewModel()).ToList();
        }
    }
}

PizzaPlace/PizzaPlace/Pages/Order.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Mappings;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;

namespace PizzaPlace.Pages
{
    public class OrderModel : PageModel
    {
        private readonly IOrderService _orderService;
        private readonly ISubscriptionService subscriptionService;

        public OrderModel(IOrderService orderService, ISubscriptionService subscriptionService)
        {
            _orderService = orderService;
            this.subscriptionService = subscriptionService;
        }

        [BindProperty]
        public OrderViewModel Order { get; set; }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                var newOrder = Order.ToDomainModel();
                _orderService.Create(newOrder);

                return RedirectToPage("ConfirmationPage", "OrderCompleted");
            }

            return Page();
        }

        public IActionResult OnPostSubscribe(string email)
        {
            subscriptionService.Create(email);

            return RedirectToPage("ConfirmationPage", "SubscriptionCompleted");
        }
    }
}

PizzaPlace/PizzaPlace/Pages/ConfirmationPage.cshtml
@page

@model PizzaPlace.Pages.ConfirmationPageModel

@{
    ViewData["Title"] = "Confirmation";
}

<h1 class="text-success text-center">@Model.Message</h1>

PizzaPlace/PizzaPlace/Pages/Details.cshtml
@page "/Menu/{slug}"

@model PizzaPlace.Pages.DetailsModel

@{
    ViewData["Title"] = "Details";
}


@if (Model.MenuItem != null)
{
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">@Model.MenuItem.Name</h5>
            <p class="card-text">@Model.MenuItem.Description</p>
            <p class="card-text"><small class="text-muted">@Model.MenuItem.Price @Model.MenuItem.Currency</small></p>
        </div>
        <img src="@Model.MenuItem.ImageUrl" class="card-img-bottom" alt="...">
    </div>
}


@if (Model.ErrorMessage != null)
{
    <h2 class="text-danger">@Model.ErrorMessage</h2>
}

PizzaPlace/PizzaPlace/Pages/Home.cshtml
@page
@model HomeModel
@{
    ViewData["Title"] = "Home page";
}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="https://www.delonghi.com/Global/recipes/multifry/pizza_fresca.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="https://cdn.britannica.com/08/177308-050-94D9D6BE/Food-Pizza-Basil-Tomato.jpg" class="d-block w-100" alt="...">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

@foreach (var offer in Model.Offers)
{
    <div class="card mt-4 text-center">
        <div class="card-body">
            <h2 class="card-title">@offer.Title</h2>
            <p class="card-text">@offer.Description</p>
            <p class="card-text">Valid to: @offer.ValidTo.ToString("dd-MM-yyyy")</p>
        </div>
    </div>
}

PizzaPlace/PizzaPlace/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="https://www.delonghi.com/Global/recipes/multifry/pizza_fresca.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="https://cdn.britannica.com/08/177308-050-94D9D6BE/Food-Pizza-Basil-Tomato.jpg" class="d-block w-100" alt="...">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

@foreach (var offer in Model.Offers)
{
    <div class="card mt-4 text-center">
        <div class="card-body">
            <h2 class="card-title">@offer.Title</h2>
            <p class="card-text">@offer.Description</p>
            <p class="card-text">Valid to: @offer.ValidTo.ToString("dd-MM-yyyy")</p>
        </div>
    </div>
}

PizzaPlace/PizzaPlace/Pages/Menu.cshtml
@page

@model PizzaPlace.Pages.MenuModel

@{
    ViewData["Title"] = "Menu";
}

@section Styles{
    <link href="/css/menu.css" rel="stylesheet" />
}

<div class="row">
    @foreach (var item in Model.MenuItems)
    {
        <div class="col-md-6">
            <div class="card mb-3 border-0 menuItem">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img class=" rounded-circle menuItemImage" src="@item.ImageUrl" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">@item.Name</h5>
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><small class="text-muted">@item.Price @item.Currency</small></p>
                            <a asp-page="Details" asp-route-slug="@item.Slug">See more</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

PizzaPlace/PizzaPlace/Pages/Order.cshtml
@page
@model PizzaPlace.Pages.OrderModel

@{
    ViewData["Title"] = "Order";
}

<div class="container" style="background-color:#dadada; margin-top:20px; padding:20px;">
    <form asp-page="Order" method="post">
        <div class="form-group">
            <label asp-for="@Model.Order.Name">Name:</label>
            <input type="text" asp-for="@Model.Order.Name" class="form-control" placeholder="Enter name" required />
            <span asp-validation-for="@Model.Order.Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Order.Surname">Surname:</label>
            <input type="text" asp-for="@Model.Order.Surname" class="form-control" placeholder="Enter surname" required />
            <span asp-validation-for="@Model.Order.Surname" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Order.Address">Address:</label>
            <input type="text" asp-for="@Model.Order.Address" class="form-control" placeholder="Enter address" required />
            <span asp-validation-for="@Model.Order.Address" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Order.Phone">Phone:</label>
            <input type="text" asp-for="@Model.Order.Phone" class="form-control" placeholder="Enter phone" required />
            <span asp-validation-for="@Model.Order.Phone" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Order.Message">Message:</label>
            <textarea asp-for="@Model.Order.Message" class="form-control" placeholder="Enter message" required></textarea>
            <span asp-validation-for="@Model.Order.Message" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Order</button>
    </form>
</div>

<div class="container" style="background-color:#dadada; margin-top:20px; padding:20px;">
    <form asp-page="Order" asp-page-handler="Subscribe" method="post">
        <h1>Subscribe:</h1>
        <div class="form-group">
            <label for="subscriptionEmail">Email:</label>
            <input class="form-control" type="email" name="email" id="subscriptionEmail" placeholder="Enter email" required />
            <span class="form-text text-muted">We'll never share your email with anyone else</span>
        </div>
        <button type="submit" class="btn btn-primary">Subscribe</button>
    </form>
</div>